/**
 * 중국어 초고속 연상암기 新HSK 5급 단어장
 * - book_scans 교재 스캔 데이터 100% 정합성 반영 (외래 어휘 배제)
 * - 1강 가정, 일상생활 (001~045) 및 2강 외모, 패션 (046~060)
 * - 한자 파자 연상 암기 비법 & 교재 실전 예문 탑재
 */

const HSK5_VOCAB = [
  {
    "id": 1,
    "no": "001",
    "hanzi": "家庭",
    "pinyin": "jiātíng",
    "partOfSpeech": "명",
    "meaning": "가정",
    "theme": "1강 가정, 일상생활",
    "image": "images/jiating.jpg",
    "mnemonic": "庭 집안, 뜰 >>> 广 집은 항상 廴 걸어 되돌아오는 곳이며, 壬 짊어진 것들을 내려놓는 곳\n家 집 + 庭 집안",
    "exampleCn": "小明的<strong>家庭</strong>非常美满。",
    "examplePinyin": "Xiǎomíng de jiātíng fēicháng měimǎn.",
    "exampleKo": "샤오밍의 가정은 매우 원만하다.",
    "collocation": "家庭美满 (가정이 원만하다) · 幸福家庭"
  },
  {
    "id": 2,
    "no": "002",
    "hanzi": "家乡",
    "pinyin": "jiāxiāng",
    "partOfSpeech": "명",
    "meaning": "고향",
    "theme": "1강 가정, 일상생활",
    "image": "images/jiaxiang.jpg",
    "mnemonic": "家 집 + 乡 시골, 마을, 구역 (鄕 시골 향의 간화 - 乡)",
    "exampleCn": "你的<strong>家乡</strong>是哪儿的？",
    "examplePinyin": "Nǐ de jiāxiāng shì nǎr de?",
    "exampleKo": "당신의 고향은 어디입니까?",
    "collocation": "美丽的家乡 (아름다운 고향) · 热爱家乡"
  },
  {
    "id": 3,
    "no": "003",
    "hanzi": "亲自",
    "pinyin": "qīnzì",
    "partOfSpeech": "부",
    "meaning": "직접, 몸소",
    "theme": "1강 가정, 일상생활",
    "image": "images/qinzi.jpg",
    "mnemonic": "亲 친히 自 자기가",
    "exampleCn": "小明<strong>亲自</strong>下厨给父母做饭。",
    "examplePinyin": "Xiǎomíng qīnzì xiàchú gěi fùmǔ zuòfàn.",
    "exampleKo": "샤오밍은 직접 요리해서 부모님께 밥을 드렸다.",
    "collocation": "亲自下厨 (직접 요리하다) · 亲自体验"
  },
  {
    "id": 4,
    "no": "004",
    "hanzi": "体贴",
    "pinyin": "tǐtiē",
    "partOfSpeech": "동",
    "meaning": "자상하게 돌보다",
    "theme": "1강 가정, 일상생활",
    "image": "images/titie.jpg",
    "mnemonic": "体 몸 >>> 亻 사람의 本 근본은 몸\n贴 붙이다, 붙다, 메우다 >>> 贝 재물을 占 점령해 잔고를 메우다\n体 몸을 贴 붙이고 자상하게 돌보다",
    "exampleCn": "男朋友总是<strong>体贴</strong>入微地照顾着我。",
    "examplePinyin": "Nánpéngyou zǒngshì tǐtiē rùwēi de zhàogù zhe wǒ.",
    "exampleKo": "남자친구는 항상 나를 자상하게 돌봐준다.",
    "collocation": "体贴入微 (더없이 자상하다) · 温柔体贴"
  },
  {
    "id": 5,
    "no": "005",
    "hanzi": "外公",
    "pinyin": "wàigōng",
    "partOfSpeech": "명",
    "meaning": "외할아버지",
    "theme": "1강 가정, 일상생활",
    "image": "images/waigong.jpg",
    "mnemonic": "외(外)와 공(친족에 대한 호칭 + 남자에 대한 존칭)이 합쳐져 외할아버지라고 생각하기",
    "exampleCn": "小明过年期间，去<strong>外公</strong>家拜年了。",
    "examplePinyin": "Xiǎomíng guònián qījiān, qù wàigōng jiā bàinián le.",
    "exampleKo": "샤오밍은 설날에 외할아버지 댁에 세배를 하러 갔다.",
    "collocation": "去外公家拜年 (외할아버지 댁에 세배 가다) · 探望外公"
  },
  {
    "id": 6,
    "no": "006",
    "hanzi": "姥姥",
    "pinyin": "lǎolao",
    "partOfSpeech": "명",
    "meaning": "외할머니",
    "theme": "1강 가정, 일상생활",
    "image": "images/laolao.jpg",
    "mnemonic": "女 여성인데 老 늙은 - 외할머니",
    "exampleCn": "小明的<strong>姥姥</strong>生病了。",
    "examplePinyin": "Xiǎomíng de lǎolao shēngbìng le.",
    "exampleKo": "샤오밍의 외할머니가 병이 났다.",
    "collocation": "生病了 (병이 났다) · 照顾姥姥"
  },
  {
    "id": 7,
    "no": "007",
    "hanzi": "舅舅",
    "pinyin": "jiùjiu",
    "partOfSpeech": "명",
    "meaning": "외숙부, 외삼촌",
    "theme": "1강 가정, 일상생활",
    "image": "images/jiujiu.jpg",
    "mnemonic": "臼 절구를 들어주는 男 남성 - 부탁할 때는 삼촌이 비교적 친근한 호칭이니, 절구 같은 무거운 것들을 들 때, 숙부, 삼촌에게 부탁했다고 연상",
    "exampleCn": "这位是我的<strong>舅舅</strong>。",
    "examplePinyin": "Zhè wèi shì wǒ de jiùjiu.",
    "exampleKo": "이 분은 저의 외삼촌입니다.",
    "collocation": "这位是我的舅舅 (이 분은 외삼촌입니다) · 亲舅舅"
  },
  {
    "id": 8,
    "no": "008",
    "hanzi": "姑姑",
    "pinyin": "gūgu",
    "partOfSpeech": "명",
    "meaning": "고모",
    "theme": "1강 가정, 일상생활",
    "image": "images/gugu.jpg",
    "mnemonic": "姑 시어머니, 고모 >>> 女 여성(뜻 부분) + 古 고(음 부분)",
    "exampleCn": "我<strong>姑姑</strong>做饭的手艺一绝。",
    "examplePinyin": "Wǒ gūgu zuòfàn de shǒuyì yìjué.",
    "exampleKo": "우리 고모의 요리 솜씨는 일품이다.",
    "collocation": "手艺一绝 (요리 솜씨가 일품이다) · 姑姑做饭"
  },
  {
    "id": 9,
    "no": "009",
    "hanzi": "兄弟",
    "pinyin": "xiōngdì",
    "partOfSpeech": "명",
    "meaning": "형제",
    "theme": "1강 가정, 일상생활",
    "image": "images/xiongdi.jpg",
    "mnemonic": "兄 형 弟 제",
    "exampleCn": "<strong>兄弟</strong>之间要和睦相处。",
    "examplePinyin": "Xiōngdì zhījiān yào hémù xiāngchǔ.",
    "exampleKo": "형제간에 화목하게 지내야 한다.",
    "collocation": "和睦相处 (화목하게 지내다) · 兄弟情深"
  },
  {
    "id": 10,
    "no": "010",
    "hanzi": "老婆",
    "pinyin": "lǎopo",
    "partOfSpeech": "명",
    "meaning": "아내, 마누라",
    "theme": "1강 가정, 일상생활",
    "image": "images/laopo.jpg",
    "mnemonic": "婆 할머니 >>> 끝없는 · 波 물결파처럼 고단한 인생을 살아온 女 여성인 할머니\n* 波 물결 >>> 氵 물의 겉 표면 皮 껍데기는 물결이다\n老 늙은 婆 할머니가 될 때까지 평생 살아야 하는 마누라",
    "exampleCn": "我在结婚纪念日的时候给<strong>老婆</strong>买了一束玫瑰花做礼物。",
    "examplePinyin": "Wǒ zài jiéhūn jìnianrì de shíhou gěi lǎopo mǎile yí shù méiguīhuā zuò lǐwù.",
    "exampleKo": "나는 결혼기념일에 아내에게 장미꽃 한 송이를 선물로 사 주었다.",
    "collocation": "给老婆买礼物 (아내에게 선물을 사주다) · 老公老婆"
  },
  {
    "id": 11,
    "no": "011",
    "hanzi": "太太",
    "pinyin": "tàitai",
    "partOfSpeech": "명",
    "meaning": "부인, 마님, 처",
    "theme": "1강 가정, 일상생활",
    "image": "images/taitai.jpg",
    "mnemonic": "요즘엔 부인이 남편에게 아주 太 크고 太 큰 존재",
    "exampleCn": "我的<strong>太太</strong>是一位非常温柔体贴的人。",
    "examplePinyin": "Wǒ de tàitai shì yí wèi fēicháng wēnróu tǐtiē de rén.",
    "exampleKo": "나의 아내는 매우 부드럽고 자상한 사람이다.",
    "collocation": "温柔体贴 (부드럽고 자상하다) · 太太与先生"
  },
  {
    "id": 12,
    "no": "012",
    "hanzi": "长辈",
    "pinyin": "zhǎngbèi",
    "partOfSpeech": "명",
    "meaning": "손윗사람, 연장자",
    "theme": "1강 가정, 일상생활",
    "image": "images/zhangbei.jpg",
    "mnemonic": "辈 무리 >>> 非 아니 타다 车 수레에 - 수레에 다 못 탈 정도로 사람 무리가 너무 많다\n나이가 长 긴 사람들의 辈 무리 - 연장자",
    "exampleCn": "我们应该尊敬<strong>长辈</strong>。",
    "examplePinyin": "Wǒmen yīnggāi zūnjìng zhǎngbèi.",
    "exampleKo": "우리는 웃어른을 존경해야 한다.",
    "collocation": "尊敬长辈 (웃어른을 존경하다) · 孝敬长辈"
  },
  {
    "id": 13,
    "no": "013",
    "hanzi": "年纪",
    "pinyin": "niánjì",
    "partOfSpeech": "명",
    "meaning": "나이, 연령",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "纪 단서, 벼리(굵은 줄) >>> 纟 실의 己 몸에 해당하는 굵은 줄\n年 년도가 지나가는 纪 단서가 되는 것 - 나이",
    "exampleCn": "你多大<strong>年纪</strong>了？",
    "examplePinyin": "Nǐ duō dà niánjì le?",
    "exampleKo": "혹시 나이가 어떻게 되세요?",
    "collocation": "多大年纪 (연세가 어떻게 되다) · 年纪轻轻"
  },
  {
    "id": 14,
    "no": "014",
    "hanzi": "姑娘",
    "pinyin": "gūniang",
    "partOfSpeech": "명",
    "meaning": "아가씨, 젊은 여자, 딸",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "姑 시어머니, 고모 >>> 女 여성 + 古 고\n娘 아가씨 >>> 女 여자가 良 어질고 좋다 - 젊은 여자에게 낭자라고 부르는 사례",
    "exampleCn": "<strong>灰姑娘</strong>",
    "examplePinyin": "Huīgūniang",
    "exampleKo": "신데렐라",
    "collocation": "年轻姑娘 (젊은 아가씨) · 漂亮姑娘"
  },
  {
    "id": 15,
    "no": "015",
    "hanzi": "宠物",
    "pinyin": "chǒngwù",
    "partOfSpeech": "명",
    "meaning": "애완동물",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "宠 사랑하다 >>> 宀 집에서 아이에게 龙 용처럼 큰 인물이 되라고 사랑을 주다\n宠 사랑을 주게 되는 物 대상 - 애완동물",
    "exampleCn": "这家公寓是禁止住户饲养<strong>宠物</strong>的。",
    "examplePinyin": "Zhè jiā gōngyù shì jìnzhǐ zhùhù sìyǎng chǒngwù de.",
    "exampleKo": "이 아파트는 입주민이 애완동물을 기르는 것을 금지한다.",
    "collocation": "饲养宠物 (반려동물을 기르다) · 宠物狗"
  },
  {
    "id": 16,
    "no": "016",
    "hanzi": "主人",
    "pinyin": "zhǔrén",
    "partOfSpeech": "명",
    "meaning": "주인",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "主 주인 人 인 - 사물이나 장소를 주관하는 사람",
    "exampleCn": "小狗跑到<strong>主人</strong>面前摇着尾巴撒娇。",
    "examplePinyin": "Xiǎogǒu pǎodào zhǔrén miànqián yáozhe wěiba sājiāo.",
    "exampleKo": "강아지가 주인에게 달려가 꼬리를 흔들며 어리광을 부린다.",
    "collocation": "真正的主人 (진정한 주인) · 家里主人"
  },
  {
    "id": 17,
    "no": "017",
    "hanzi": "隔壁",
    "pinyin": "gébì",
    "partOfSpeech": "명",
    "meaning": "이웃집, 옆집",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "隔 사이를 떼다 >>> 阝 막다, 一 한 口 구멍을 冂 둘러서 분리하다\n壁 벽 >>> 土 흙을 쌓아 만든 벽",
    "exampleCn": "小明经常陪<strong>隔壁</strong>的老奶奶聊天。",
    "examplePinyin": "Xiǎomíng jīngcháng péi gébì de lǎonǎinai liáotiān.",
    "exampleKo": "샤오밍은 자주 옆집 할머니와 이야기를 나눈다.",
    "collocation": "隔壁邻居 (옆집 이웃) · 住在隔壁"
  },
  {
    "id": 18,
    "no": "018",
    "hanzi": "好客",
    "pinyin": "hàokè",
    "partOfSpeech": "형",
    "meaning": "손님을 잘 대하는, 손님을 좋아하는",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "好 좋아하다 客 손님을 >>> 손님 맞이를 즐거워하고 융숭하게 대접하다",
    "exampleCn": "这个寨子里的人非常热情<strong>好客</strong>。",
    "examplePinyin": "Zhège zhàizi lǐ de rén fēicháng rèqíng hàokè.",
    "exampleKo": "이 마을 사람들은 매우 친절하고 손님 접대를 좋아한다.",
    "collocation": "热情好客 (친절하고 손님 대접을 좋아하다)"
  },
  {
    "id": 19,
    "no": "019",
    "hanzi": "问候",
    "pinyin": "wènhòu",
    "partOfSpeech": "동",
    "meaning": "안부를 묻다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "候 기후, 조짐 >>> 그 사람의 상황(기후)을 问 묻다",
    "exampleCn": "请帮我传达一下我对她的<strong>问候</strong>。",
    "examplePinyin": "Qǐng bāng wǒ chuándá yíxià wǒ duì tā de wènhòu.",
    "exampleKo": "그녀에 대한 나의 안부를 전해주세요.",
    "collocation": "传达问候 (안부를 전하다) · 致以亲切问候"
  },
  {
    "id": 20,
    "no": "020",
    "hanzi": "看望",
    "pinyin": "kànwàng",
    "partOfSpeech": "동",
    "meaning": "방문하다, 찾아가 보다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "看 보다 望 바라보다 >>> 어른이나 환자를 찾아가 잘 지내시는지 살피다",
    "exampleCn": "小明去医院<strong>看望</strong>了他的姥姥。",
    "examplePinyin": "Xiǎomíng qù yīyuàn kànwàng le tā de lǎolao.",
    "exampleKo": "샤오밍은 병원에 가서 그의 외할머니를 뵈었다.",
    "collocation": "看望病人 (환자를 문병하다) · 看望老人"
  },
  {
    "id": 21,
    "no": "021",
    "hanzi": "孝顺",
    "pinyin": "xiàoshùn",
    "partOfSpeech": "동",
    "meaning": "효도하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "孝 효도 >>> 耂 늙은 부모를 업은 子 자식의 '효'\n顺 따르다 >>> 부모님의 뜻을 잘 따르다",
    "exampleCn": "小明十分<strong>孝顺</strong>家里的老人。",
    "examplePinyin": "Xiǎomíng shífēn xiàoshùn jiālǐ de lǎorén.",
    "exampleKo": "샤오밍은 집안의 노인에게 매우 효도한다.",
    "collocation": "孝顺父母 (부모님께 효도하다) · 懂得孝顺"
  },
  {
    "id": 22,
    "no": "022",
    "hanzi": "尊敬",
    "pinyin": "zūnjìng",
    "partOfSpeech": "동",
    "meaning": "존경하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "尊 높이다, 술을 들어 예를 표하다\n敬 공경하다 >>> 정성껏 공경하고 우러러보다",
    "exampleCn": "学生应该<strong>尊敬</strong>老师。",
    "examplePinyin": "Xuéshēng yīnggāi zūnjìng lǎoshī.",
    "exampleKo": "학생은 마땅히 선생님을 존경해야 한다.",
    "collocation": "尊敬师长 (선생님과 어른을 존경하다) · 值得尊敬"
  },
  {
    "id": 23,
    "no": "023",
    "hanzi": "有利",
    "pinyin": "yǒulì",
    "partOfSpeech": "형",
    "meaning": "유리한, 이로운",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "禾 벼를 베려면 刂 칼이 날카로워야 이득이다\n有 있다 利 이익 >>> 이로움과 도움이 되다",
    "exampleCn": "多运动<strong>有利</strong>于身体健康。",
    "examplePinyin": "Duō yùndòng yǒulì yú shēntǐ jiànkāng.",
    "exampleKo": "운동을 많이 하면 건강에 이롭다.",
    "collocation": "有利于健康 (건강에 이롭다) · 有利条件"
  },
  {
    "id": 24,
    "no": "024",
    "hanzi": "培养",
    "pinyin": "péiyǎng",
    "partOfSpeech": "동",
    "meaning": "양성하다, 육성하다, 기르다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "培 흙을 북돋우다\n养 기르다 >>> 가축과 식물, 인재를 정성껏 북돋아 키우다",
    "exampleCn": "他的父母从小<strong>培养</strong>他当医生。",
    "examplePinyin": "Tā de fùmǔ cóngxiǎo péiyǎng tā dāng yīshēng.",
    "exampleKo": "그의 부모님은 어릴 때부터 그를 의사가 되도록 키웠다.",
    "collocation": "培养习惯 (습관을 기르다) · 培养人才"
  },
  {
    "id": 25,
    "no": "025",
    "hanzi": "夸",
    "pinyin": "kuā",
    "partOfSpeech": "동",
    "meaning": "과장하다, 칭찬하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "亏 모자란 점을 덮으려고 그 위에 大 크게 자랑하고 칭찬하다",
    "exampleCn": "小明<strong>夸</strong>妈妈做的饭好吃。",
    "examplePinyin": "Xiǎomíng kuā māma zuò de fàn hǎochī.",
    "exampleKo": "샤오밍은 엄마가 만든 밥이 맛있다고 칭찬했다.",
    "collocation": "连连夸奖 (연신 칭찬하다) · 夸大事实"
  },
  {
    "id": 26,
    "no": "026",
    "hanzi": "靠",
    "pinyin": "kào",
    "partOfSpeech": "동",
    "meaning": "기대다, 닿다, 의지하다, 믿다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "告 + 非 >>> 벽에 몸을 기대듯 누군가에게 의지하거나 스스로를 믿다",
    "exampleCn": "做任何事情都应该<strong>靠</strong>自己。",
    "examplePinyin": "Zuò rènhé shìqing dōu yīnggāi kào zìjǐ.",
    "exampleKo": "무슨 일을 하든지 반드시 자신을 믿어야 한다.",
    "collocation": "依靠自己 (자신에게 의지하다) · 靠谱"
  },
  {
    "id": 27,
    "no": "027",
    "hanzi": "沟通",
    "pinyin": "gōutōng",
    "partOfSpeech": "동",
    "meaning": "소통하다, 교류하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "沟 도랑에서 만나 서로 通 통하듯 생각과 말을 나누다",
    "exampleCn": "计划执行之前，一定要和各个部门<strong>沟通</strong>好流程。",
    "examplePinyin": "Jìhuà zhíxíng zhīqián, yídìng yào hé gègè bùmén gōutōng hǎo liúchéng.",
    "exampleKo": "계획을 실행하기 전에 반드시 각 부서와 과정을 잘 소통해야 한다.",
    "collocation": "沟通交流 (소통하고 교류하다) · 善于沟通"
  },
  {
    "id": 28,
    "no": "028",
    "hanzi": "讲究",
    "pinyin": "jiǎngjiu",
    "partOfSpeech": "동",
    "meaning": "중요시하다, 신경을 쓰다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "讲 설명할 정도로 깊이 있게 究 연구하고 파고들어 주의를 기울이다",
    "exampleCn": "做事情要<strong>讲究</strong>方法。",
    "examplePinyin": "Zuò shìqing yào jiǎngjiu fāngfǎ.",
    "exampleKo": "일을 할 때는 방법을 강구해야 한다.",
    "collocation": "讲究卫生 (위생에 신경 쓰다) · 讲究礼仪"
  },
  {
    "id": 29,
    "no": "029",
    "hanzi": "成长",
    "pinyin": "chéngzhǎng",
    "partOfSpeech": "동",
    "meaning": "성장하다, 자라다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "成 이루어지며 长 길고 높게 쑥쑥 자라나다",
    "exampleCn": "小明在一个充满爱的家庭环境中<strong>成长</strong>。",
    "examplePinyin": "Xiǎomíng zài yí gè chōngmǎn ài de jiātíng huánjìng zhōng chéngzhǎng.",
    "exampleKo": "샤오밍은 사랑이 넘치는 가정 환경에서 자랐다.",
    "collocation": "健康成长 (건강하게 자라다) · 茁壮成长"
  },
  {
    "id": 30,
    "no": "030",
    "hanzi": "形成",
    "pinyin": "xíngchéng",
    "partOfSpeech": "동",
    "meaning": "형성하다, 구성하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "形 모양을 갖추어 成 완성되다 - 형성되다",
    "exampleCn": "这对双胞胎，一个活泼，一个安静，他们的性格<strong>形成</strong>了鲜明的对比。",
    "examplePinyin": "Zhè duì shuāngbāotāi, yí gè huópo, yí gè ānjìng, tāmen de xìnggé xíngchéng le xiānmíng de duìbǐ.",
    "exampleKo": "한 명은 활발하고, 한명은 조용한, 이 쌍둥이의 성격은 분명한 대조를 이룬다.",
    "collocation": "形成对比 (대조를 이루다) · 形成习惯"
  },
  {
    "id": 31,
    "no": "031",
    "hanzi": "疼爱",
    "pinyin": "téng'ài",
    "partOfSpeech": "동",
    "meaning": "매우 귀여워하다, 매우 사랑하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "마음이 疼 찌르르 아플 정도로 爱 깊이 사랑하고 아끼다",
    "exampleCn": "姑姑很<strong>疼爱</strong>我，经常给我买玩具。",
    "examplePinyin": "Gūgu hěn téng'ài wǒ, jīngcháng gěi wǒ mǎi wánjù.",
    "exampleKo": "고모는 나를 아껴주어, 늘 장난감을 사주곤 했다.",
    "collocation": "备受疼爱 (지극한 사랑을 받다) · 疼爱孩子"
  },
  {
    "id": 32,
    "no": "032",
    "hanzi": "宝贝",
    "pinyin": "bǎobèi",
    "partOfSpeech": "명",
    "meaning": "보배, 귀여운아이",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "宝 옥을 모시듯 소중한 贝 재물 - 귀하디귀한 자식",
    "exampleCn": "每个人都是父母的<strong>宝贝</strong>孩子。",
    "examplePinyin": "Měi gè rén dōu shì fùmǔ de bǎobèi háizi.",
    "exampleKo": "모든 사람은 부모의 귀한 자식이다.",
    "collocation": "宝贝儿子 (귀한 아들) · 稀世宝贝"
  },
  {
    "id": 33,
    "no": "033",
    "hanzi": "相处",
    "pinyin": "xiāngchǔ",
    "partOfSpeech": "동",
    "meaning": "함께 살다, 함께 지내다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "相 서로 같은 处 곳에 머무르며 사이좋게 살아가다",
    "exampleCn": "这个人的性格非常好，和他<strong>相处</strong>起来感觉很舒适。",
    "examplePinyin": "Zhège rén de xìnggé fēicháng hǎo, hé tā xiāngchǔ qǐlai gǎnjué hěn shūshì.",
    "exampleKo": "이 사람은 성격이 매우 좋아서 그와 함께 지내면 편안함을 느낀다.",
    "collocation": "友好相处 (우호적으로 지내다) · 和睦相处"
  },
  {
    "id": 34,
    "no": "034",
    "hanzi": "家务",
    "pinyin": "jiāwù",
    "partOfSpeech": "명",
    "meaning": "가사, 집안일",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "家 집안에서 务 힘써 처리해야 하는 모든 살림살이",
    "exampleCn": "你平时在家里会做<strong>家务</strong>吗？",
    "examplePinyin": "Nǐ píngshí zài jiālǐ huì zuò jiāwù ma?",
    "exampleKo": "당신은 평소에 집에서 집안일을 합니까?",
    "collocation": "分担家务 (집안일을 분담하다) · 做家务"
  },
  {
    "id": 35,
    "no": "035",
    "hanzi": "自由",
    "pinyin": "zìyóu",
    "partOfSpeech": "명",
    "meaning": "자유, 자유로운",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "自 스스로 由 말미암다 - 얽매이지 않고 뜻대로 하다",
    "exampleCn": "笼子里的鸟向往着在空中<strong>自由</strong>地飞翔。",
    "examplePinyin": "Lóngzi lǐ de niǎo xiàngwǎng zhe zài kōngzhōng zìyóu de fēixiáng.",
    "exampleKo": "새장 속의 새들은 하늘을 자유롭게 날아다니는 것을 동경한다.",
    "collocation": "自由自在 (자유자재하다) · 追求自由"
  },
  {
    "id": 36,
    "no": "036",
    "hanzi": "嫁",
    "pinyin": "jià",
    "partOfSpeech": "동",
    "meaning": "시집가다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "女 여자가 시댁 家 집으로 들어가 가정을 이루다",
    "exampleCn": "你愿意<strong>嫁</strong>给我吗？",
    "examplePinyin": "Nǐ yuànyì jià gěi wǒ ma?",
    "exampleKo": "나랑 결혼 해줄래?",
    "collocation": "嫁人 (시집가다) · 出嫁"
  },
  {
    "id": 37,
    "no": "037",
    "hanzi": "娶",
    "pinyin": "qǔ",
    "partOfSpeech": "동",
    "meaning": "아내를 얻다, 장가가다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "取 가지다, 맞이하다 + 女 여자 - 아내를 맞아들이다",
    "exampleCn": "小明<strong>娶</strong>到了又漂亮又贤惠的媳妇儿。",
    "examplePinyin": "Xiǎomíng qǔdào le yòu piàoliang yòu xiánhuì de xífur.",
    "exampleKo": "샤오밍은 예쁘고 현명한 아내를 얻었다.",
    "collocation": "娶妻生子 (아내를 얻고 자식을 낳다) · 迎娶"
  },
  {
    "id": 38,
    "no": "038",
    "hanzi": "婚礼",
    "pinyin": "hūnlǐ",
    "partOfSpeech": "명",
    "meaning": "혼례, 결혼식",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "婚 혼인할 때 礼 신과 가족에게 예를 갖추어 올리는 의식",
    "exampleCn": "小明今天去参加了朋友的<strong>婚礼</strong>。",
    "examplePinyin": "Xiǎomíng jīntiān qù cānjiā le péngyou de hūnlǐ.",
    "exampleKo": "샤오밍은 오늘 친구의 결혼식에 갔다.",
    "collocation": "举办婚礼 (결혼식을 올리다) · 参加婚礼"
  },
  {
    "id": 39,
    "no": "039",
    "hanzi": "婚姻",
    "pinyin": "hūnyīn",
    "partOfSpeech": "명",
    "meaning": "혼인, 결혼",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "婚 남녀가 만나 姻 인연을 맺어 평생 함께하는 제도",
    "exampleCn": "世上真的有完美的<strong>婚姻</strong>吗？",
    "examplePinyin": "Shìshàng zhēnde yǒu wánměi de hūnyīn ma?",
    "exampleKo": "세상에 정말 완벽한 결혼이 있을까?",
    "collocation": "婚姻生活 (결혼 생활) · 美满婚姻"
  },
  {
    "id": 40,
    "no": "040",
    "hanzi": "离婚",
    "pinyin": "líhūn",
    "partOfSpeech": "동",
    "meaning": "이혼하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "离 떠나다 + 婚 혼인 - 결혼 관계를 정리하고 갈라서다",
    "exampleCn": "自从父母<strong>离婚</strong>后，小明就变得沉默寡言了。",
    "examplePinyin": "Zìcóng fùmǔ líhūn hòu, Xiǎomíng jiù biànde chénmò guǎyán le.",
    "exampleKo": "부모님이 이혼한 후부터 샤오밍은 과묵해졌다.",
    "collocation": "协议离婚 (협의 이혼하다) · 办理离婚"
  },
  {
    "id": 41,
    "no": "041",
    "hanzi": "登记",
    "pinyin": "dēngjì",
    "partOfSpeech": "동",
    "meaning": "정식으로 등기하다, 등록하다",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "登 관청에 올라 记 장부에 낱낱이 기록하여 올리다",
    "exampleCn": "小明正在<strong>登记</strong>产品的出库数量。",
    "examplePinyin": "Xiǎomíng zhèngzài dēngjì chǎnpǐn de chūkù shùliàng.",
    "exampleKo": "샤오밍은 지금 제품의 출고 수량을 등록하고 있다.",
    "collocation": "登记结婚 (혼인 신고하다) · 登记入册"
  },
  {
    "id": 42,
    "no": "042",
    "hanzi": "人生",
    "pinyin": "rénshēng",
    "partOfSpeech": "명",
    "meaning": "인생",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "人 사람이 生 태어나 살아가는 한평생의 여정",
    "exampleCn": "<strong>人生</strong>是充满挑战的。",
    "examplePinyin": "Rénshēng shì chōngmǎn tiǎozhàn de.",
    "exampleKo": "인생은 도전으로 가득 차 있다.",
    "collocation": "人生道路 (인생길) · 人生哲学"
  },
  {
    "id": 43,
    "no": "043",
    "hanzi": "一辈子",
    "pinyin": "yíbèizi",
    "partOfSpeech": "명",
    "meaning": "한평생, 일생",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "一 한 辈 무리의 사건들이 이어지는 子 일평생",
    "exampleCn": "小明经历了车祸后，手臂上<strong>一辈子</strong>都会留下这块疤。",
    "examplePinyin": "Xiǎomíng jīnglì le chēhuò hòu, shǒubì shang yíbèizi dōu huì liúxià zhè kuài bā.",
    "exampleKo": "샤오밍은 교통사고를 겪은 후 팔에 평생 이 흉터가 남을 것입니다.",
    "collocation": "一辈子的朋友 (평생의 친구) · 辛苦了一辈子"
  },
  {
    "id": 44,
    "no": "044",
    "hanzi": "通常",
    "pinyin": "tōngcháng",
    "partOfSpeech": "부",
    "meaning": "통상적으로",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "通 널리 常 늘 그러하듯 - 일반적인 상황",
    "exampleCn": "我的爷爷<strong>通常</strong>每天早上5点起床。",
    "examplePinyin": "Wǒ de yéye tōngcháng měitiān zǎoshang wǔ diǎn qǐchuáng.",
    "exampleKo": "나의 할아버지는 보통 매일 아침 5시에 일어나신다.",
    "collocation": "通常情况下 (통상적인 상황에서는) · 通常认为"
  },
  {
    "id": 45,
    "no": "045",
    "hanzi": "团",
    "pinyin": "tuán",
    "partOfSpeech": "명",
    "meaning": "단체, 집단",
    "theme": "1강 가정, 일상생활",
    "image": null,
    "mnemonic": "囗 울타리 안에 才 재능 있는 사람들이 둥글게 모인 단체",
    "exampleCn": "比赛<strong>团</strong>队获得了优异的成绩。",
    "examplePinyin": "Bǐsài tuánduì huòdé le yōuyì de chéngjì.",
    "exampleKo": "경기단은 우수한 성적을 거두었다.",
    "collocation": "团结一致 (일치단결하다) · 旅行团"
  },
  {
    "id": 46,
    "no": "046",
    "hanzi": "个性",
    "pinyin": "gèxìng",
    "partOfSpeech": "명",
    "meaning": "개성",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "个 개별적인 사람이 지닌 性 본성과 특징 - 개성",
    "exampleCn": "我觉得他是一个十分有<strong>个性</strong>的人。",
    "examplePinyin": "Wǒ juéde tā shì yí gè shífēn yǒu gèxìng de rén.",
    "exampleKo": "나는 그가 매우 개성 있는 사람이라고 생각한다.",
    "collocation": "很有个性 (개성이 뚜렷하다) · 个性签名"
  },
  {
    "id": 47,
    "no": "047",
    "hanzi": "独特",
    "pinyin": "dútè",
    "partOfSpeech": "형",
    "meaning": "독특한, 특수한",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "独 홀로 特 특별하다 >>> 남들과 다르게 유일하고 두드러지다",
    "exampleCn": "小明的想法总是很<strong>独特</strong>。",
    "examplePinyin": "Xiǎomíng de xiǎngfǎ zǒngshì hěn dútè.",
    "exampleKo": "샤오밍의 생각은 항상 독특하다.",
    "collocation": "独特风格 (독특한 스타일) · 独特性"
  },
  {
    "id": 48,
    "no": "048",
    "hanzi": "身材",
    "pinyin": "shēncái",
    "partOfSpeech": "명",
    "meaning": "몸매, 체격",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "身 몸의 材 재목과 골격 - 사람의 몸매와 비율",
    "exampleCn": "明星们都非常注重<strong>身材</strong>管理。",
    "examplePinyin": "Míngxīngmen dōu fēicháng zhùzhòng shēncái guǎnlǐ.",
    "exampleKo": "스타들은 몸매 관리에 신경을 많이 쓴다.",
    "collocation": "保持身材 (몸매를 유지하다) · 身材高大"
  },
  {
    "id": 49,
    "no": "049",
    "hanzi": "苗条",
    "pinyin": "miáotiao",
    "partOfSpeech": "형",
    "meaning": "날씬한",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "苗 싹과 条 가지처럼 가늘고 곧게 쭉 뻗은 날씬한 자태",
    "exampleCn": "她的<strong>身材</strong>像舞蹈生那样<strong>苗条</strong>。",
    "examplePinyin": "Tā de shēncái xiàng wǔdǎoshēng nàyàng miáotiao.",
    "exampleKo": "그녀의 몸매는 무용생처럼 날씬하다.",
    "collocation": "身材苗条 (날씬한 몸매) · 窈窕苗条"
  },
  {
    "id": 50,
    "no": "050",
    "hanzi": "显得",
    "pinyin": "xiǎnde",
    "partOfSpeech": "동",
    "meaning": "~하게 보이다, 드러나다",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "显 겉으로 밝게 드러나 ~한 인상을 주다",
    "exampleCn": "小明穿上这身衣服<strong>显得</strong>神气十足。",
    "examplePinyin": "Xiǎomíng chuānshang zhè shēn yīfu xiǎnde shénqì shízú.",
    "exampleKo": "샤오밍이 이 옷을 입으니 매우 의기양양해 보인다.",
    "collocation": "显得年轻 (젊어 보이다) · 显得格外精神"
  },
  {
    "id": 51,
    "no": "051",
    "hanzi": "表情",
    "pinyin": "biǎoqíng",
    "partOfSpeech": "명",
    "meaning": "표정",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "表 겉으로 드러난 情 마음속 감정의 모양",
    "exampleCn": "说到这件事的时候，她的<strong>表情</strong>显得有些为难。",
    "examplePinyin": "Shuōdào zhè jiàn shì de shíhou, tā de biǎoqíng xiǎnde yǒuxiē wéinán.",
    "exampleKo": "이 일을 말할 때 그녀의 표정은 약간 난처해 보였다.",
    "collocation": "面部表情 (얼굴 표정) · 表情丰富"
  },
  {
    "id": 52,
    "no": "052",
    "hanzi": "微笑",
    "pinyin": "wēixiào",
    "partOfSpeech": "동",
    "meaning": "미소 짓다, 미소",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "微 작고 잔잔하게 笑 소리 없이 방긋 웃다",
    "exampleCn": "面试官十分亲切，面带<strong>微笑</strong>地看着我。",
    "examplePinyin": "Miànshìguān shífēn qīnqiè, miàndài wēixiào de kànzhe wǒ.",
    "exampleKo": "면접관은 친절하게도 미소를 지으며 나를 바라보았다.",
    "collocation": "面带微笑 (미소를 띠다) · 甜美的微笑"
  },
  {
    "id": 53,
    "no": "053",
    "hanzi": "表面",
    "pinyin": "biǎomiàn",
    "partOfSpeech": "명",
    "meaning": "표면, 겉",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "表 겉 面 겉면 - 눈에 보이는 바깥쪽",
    "exampleCn": "看任何事物都不能只看<strong>表面</strong>。",
    "examplePinyin": "Kàn rènhé shìwù dōu bùnéng zhǐ kàn biǎomiàn.",
    "exampleKo": "어떤 사물을 보더라도 겉모습만 보면 안 된다.",
    "collocation": "表面现象 (표면적 현상) · 浮于表面"
  },
  {
    "id": 54,
    "no": "054",
    "hanzi": "方",
    "pinyin": "fāng",
    "partOfSpeech": "형",
    "meaning": "네모난",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "모서리가 반듯한 네모 모양",
    "exampleCn": "这个箱子是<strong>方</strong>的。",
    "examplePinyin": "Zhège xiāngzi shì fāng de.",
    "exampleKo": "이 상자는 네모난 것이다.",
    "collocation": "方形桌子 (네모난 탁자) · 四四方方"
  },
  {
    "id": 55,
    "no": "055",
    "hanzi": "圆",
    "pinyin": "yuán",
    "partOfSpeech": "형",
    "meaning": "둥근, 원형의",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "囗 둘레 안에 둥글게 채워진 둥근 원",
    "exampleCn": "小明的脸型偏<strong>圆</strong>，看起来可爱极了。",
    "examplePinyin": "Xiǎomíng de liǎnxíng piān yuán, kàn qǐlai kě'ài jíle.",
    "exampleKo": "샤오밍의 얼굴형은 둥근 편이어서 매우 귀여워 보인다.",
    "collocation": "圆圆的脸 (동그란 얼굴) · 团团圆圆"
  },
  {
    "id": 56,
    "no": "056",
    "hanzi": "光滑",
    "pinyin": "guānghuá",
    "partOfSpeech": "형",
    "meaning": "반들반들한, 매끄러운",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "光 빛이 나고 滑 매끄럽게 미끄러지다",
    "exampleCn": "每天洗澡后抹上身体乳会使皮肤变得更<strong>光滑</strong>。",
    "examplePinyin": "Měitiān xǐzǎo hòu mǒshang shēntǐrǔ huì shǐ pífū biànde gèng guānghuá.",
    "exampleKo": "매일 목욕 후 몸을 바르면 피부가 더욱 매끈해진다.",
    "collocation": "皮肤光滑 (피부가 매끄럽다) · 光滑平整"
  },
  {
    "id": 57,
    "no": "057",
    "hanzi": "粗糙",
    "pinyin": "cūcāo",
    "partOfSpeech": "형",
    "meaning": "까칠까칠한, 거친, 조잡한",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "米 쌀겨가 거칠듯 粗 거칠고 糙 다듬어지지 않다",
    "exampleCn": "母亲常年劳作的手摸起来很<strong>粗糙</strong>。",
    "examplePinyin": "Mǔqīn chángnián láozuò de shǒu mō qǐlai hěn cūcāo.",
    "exampleKo": "어머니의 연중 고된 손은 만져보니 까칠까칠하다.",
    "collocation": "双手粗糙 (손이 거칠다) · 质地粗糙"
  },
  {
    "id": 58,
    "no": "058",
    "hanzi": "优美",
    "pinyin": "yōuměi",
    "partOfSpeech": "형",
    "meaning": "우아하고 아름다운",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "优 뛰어나고 우수하며 美 아름답다",
    "exampleCn": "小明<strong>优美</strong>的歌声结束，全场响起一片掌声。",
    "examplePinyin": "Xiǎomíng yōuměi de gēshēng jiéshù, quánchǎng xiǎngqǐ yí piàn zhǎngshēng.",
    "exampleKo": "샤오밍의 아름다운 노랫소리가 끝나자 장내에 박수가 터져 나왔다.",
    "collocation": "动作优美 (동작이 우아하다) · 风景优美"
  },
  {
    "id": 59,
    "no": "059",
    "hanzi": "英俊",
    "pinyin": "yīngjùn",
    "partOfSpeech": "형",
    "meaning": "잘생긴, 재능이 출중한",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "英 꽃처럼 준수하고 俊 빼어난 재능과 외모를 겸비하다",
    "exampleCn": "相亲对象的样子长得很<strong>英俊</strong>但是我们没有共同话题。",
    "examplePinyin": "Xiāngqīn duìxiàng de yàngzi zhǎng de hěn yīngjùn dànshì wǒmen méiyǒu gòngtóng huàtí.",
    "exampleKo": "소개팅 상대방의 모습은 잘생겼지만 우리는 공통화제가 없다.",
    "collocation": "英俊潇洒 (준수하고 멋지다) · 年轻英俊"
  },
  {
    "id": 60,
    "no": "060",
    "hanzi": "丑",
    "pinyin": "chǒu",
    "partOfSpeech": "형",
    "meaning": "추한, 못생긴",
    "theme": "2강 외모, 패션",
    "image": null,
    "mnemonic": "보기 흉하거나 볼품없는 외모",
    "exampleCn": "这只小狗有点<strong>丑</strong>，但是做完宠物美容就会变好看的。",
    "examplePinyin": "Zhè zhī xiǎogǒu yǒudiǎn chǒu, dànshì zuòwán chǒngwù měiróng jiù huì biàn hǎokàn de.",
    "exampleKo": "이 강아지는 조금 못생겼지만 펫미용하면 예뻐질거야.",
    "collocation": "丑陋 (추악하다, 못생기다) · 丑小鸭"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = HSK5_VOCAB;
}
